[tool.ruff]
line-length = 120
exclude = [".git", "__pycache__", ".venv"]

[tool.ruff.lint]
# E (pycodestyle), W (pycodestyle warnings), F (pyflakes), D (pydocstyle), I (isort)
select = ["E", "W", "F", "D", "I"]
ignore = ["D100", "D104", "D101", "D102", "D103", "D105", "D106", "D107"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
# List of third-party packages
known-third-party = ["requests"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
strict_optional = true
no_implicit_optional = true
warn_no_return = true
check_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
ignore_missing_imports = true
strict_equality = true
warn_unused_ignores = true
warn_unreachable = true
